[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = stm32cube
monitor_speed = 115200
lib_archive = no

build_flags =
    -I lib/FreeRTOS-Kernel/include
    -I lib/FreeRTOS-Kernel/portable/GCC/ARM_CM3


[env:test_native]
platform = native
test_framework = unity
test_build_src = yes
test_filter = test_logic

lib_ignore =
    FreeRTOS-Kernel

build_flags =
    -IC:/Users/Acey/bca182-freertos-multisensor/include

build_src_filter =
    +<alarm.cpp>
    +<input.cpp>
    +<system_state.cpp>